
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdencffimqusolxqbnjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZW5jZmZpbXF1c29seHFibmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTA4ODcsImV4cCI6MjA2MDIyNjg4N30.GyJEznNyJf1w1K7gNShkpj2NF4v69ollnuQ9WgonbG0";

// Google OAuth credentials - these would normally be in environment variables
// but are included here for direct integration as requested
const GOOGLE_CLIENT_ID = "674049796284-u4jjioha7pgaubavllj8bj2u81vq0kuf.apps.googleusercontent.com";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Helper function for social sign in
export const signInWithSocial = async (provider: 'google' | 'facebook' | 'twitter' | 'linkedin') => {
  try {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: provider,
      options: {
        redirectTo: window.location.origin + '/auth/callback',
      },
    });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error signing in with social provider:', error);
    return { data: null, error };
  }
};
