// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdencffimqusolxqbnjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZW5jZmZpbXF1c29seHFibmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTA4ODcsImV4cCI6MjA2MDIyNjg4N30.GyJEznNyJf1w1K7gNShkpj2NF4v69ollnuQ9WgonbG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);